[book]
authors = ["macmarrum", "dpolivaev"]
language = "en"
multilingual = false
src = "docs"
title = "Freeplane Documentation"
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4